/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    //"aws_cognito_identity_pool_id": "us-east-1:16fa9fde-5e85-4c6e-8474-6a6622deab48",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IdhIOkkcJ",
    "aws_user_pools_web_client_id": "5oj77gsa562hkh8irp6u322ree",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

/*
Auth.configure({
  identityPoolId: process.env.VUE_APP_AWS_IDENTITY_POOL_ID,
  region: process.env.VUE_APP_AWS_REGION,
  userPoolId: process.env.VUE_APP_AWS_USER_POOL_ID,
  userPoolWebClientId: process.env.VUE_APP_AWS_USER_POOL_CLIENT_ID,
  mandatorySignIn: true,
  ...(process.env.VUE_APP_ENVIRONMENT !== 'staging'
    ? {
      cookieStorage: {
        domain: process.env.VUE_APP_AUTH_COOKIE_DOMAIN,
        path: '/',
        expires: EXPIRATION_DAYS,
        secure: process.env.NODE_ENV !== 'development',
      },
    }
    : {}),
});
 */

export default awsconfig;
